name: Lint

on: [push]

jobs:
  lint:
    name: Run ESLint & Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run Prettier
        run: yarn prettier --check .
      - name: Run ESLint
        run: yarn eslint
